apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-search.fullname" . }}-secrets
  labels:
    {{- include "jira-search.labels" . | nindent 4 }}
  annotations:
    # ArgoCD annotations to prevent auto-sync/prune of manually updated secrets
    argocd.argoproj.io/sync-options: "Prune=false"
    {{- with .Values.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  jira-pat: {{ .Values.secrets.jira_pat | b64enc | quote }}